/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ia;

import java.awt.Component;
import javax.swing.*;
import java.util.*;

/**
 *
 * @author Varun Jasti
 */
public class Base extends javax.swing.JFrame {
    
    private static ArrayList<JPanel> pList = new ArrayList<>();
    private static String user;
    private static Expenses exp;
    private static ViewExpenses viewExps;
    private static ViewTrips viewTrips;
    
    public Base() {
        initComponents();
        loadJPanels();
        showPanel(2);
    }
    
    public void setUser(String user) {
        this.user = user;
        exp.trips();
    }
    
    public String getUser() {
        return user;
    }
    
    public void showPanel(int pNum)
    {
        for (int i = 0; i < pList.size(); i++) {
            pList.get(i).setVisible(false);
        }
        if (pNum == 3) exp.trips();
        if (pNum == 5) viewExps.updateTable();
        if (pNum == 6) viewTrips.updateTable();
        pList.get(pNum - 1).setVisible(true);
    }
    
    public void loadJPanels() {
        JPanel user = new NewUser();
        JPanel login = new Login();
        exp = new Expenses();
        JPanel trip = new Trip();
        viewExps = new ViewExpenses();
        viewTrips = new ViewTrips();
        this.add(user);
        this.add(login);
        this.add(exp);
        this.add(trip);
        this.add(viewExps);
        this.add(viewTrips);
        pList.add(user);
        pList.add(login);
        pList.add(exp);
        pList.add(trip);
        pList.add(viewExps);
        pList.add(viewTrips);
        for (int i = 0; i < pList.size(); i++) {
            pList.get(i).setLocation(0, 0);
            pList.get(i).setSize(this.getContentPane().getWidth(), this.getContentPane().getHeight());
            pList.get(i).setVisible(true);
        }
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Base().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
