/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ia;

import java.io.File;
import java.io.FileInputStream;
import java.sql.*;
import javax.swing.*;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author Varun Jasti
 */
public class Expenses extends javax.swing.JPanel {

    private static File SF;

    /**
     * Creates new form Expenses
     */
    public Expenses() {
        initComponents();
        tripDrop.removeAllItems();
        typeDrop.removeAllItems();
        currDrop.removeAllItems();
        typeDrop.addItem("Transportation");
        typeDrop.addItem("Personal Meal");
        typeDrop.addItem("Business Meal");
        typeDrop.addItem("Parking");
        typeDrop.addItem("Hotel");
        typeDrop.addItem("Flight");
        typeDrop.addItem("Other");
        currDrop.addItem("USD");
        currDrop.addItem("AUD");
        currDrop.addItem("GBP");
        currDrop.addItem("Other");
        typeDrop.setSelectedIndex(-1);
        currDrop.setSelectedIndex(-1);
        setDrops(month, 1, 12);
        setDrops(day, 1, 31);
        setDrops(year, 2020, 2030);
    }

    public void setDrops(JComboBox<String> drop, int s, int e) {
        drop.removeAllItems();
        for (int i = s; i <= e; i++) {
            drop.addItem(i + "");
        }
        drop.setSelectedIndex(-1);
    }

    public void trips() {
        tripDrop.removeAllItems();
        try {
            ResultSet rs = IA.top4Trips(IA.base.getUser());
            for (int i = 0; i < 4; i++) {
                rs.next();
                tripDrop.addItem(rs.getString("trip_name"));
            }
        } catch (Exception e) {
            System.out.println("error");
        }
        tripDrop.setSelectedIndex(-1);
    }

    public void empty() {
        amountField.setText("");
        tripDrop.setSelectedIndex(-1);
        typeDrop.setSelectedIndex(-1);
        currDrop.setSelectedIndex(-1);
        selFileButton.setText("Select File");
        SF = null;
    }

    public void expense() {
        try {
            if (!(SF == null)) {
                FileInputStream fis = new FileInputStream(SF);
                if (IA.addExpense(tripDrop.getSelectedItem(), typeDrop.getSelectedItem(), currDrop.getSelectedItem(), amountField.getText(), year.getSelectedItem() + "-" + month.getSelectedItem() + "-" + day.getSelectedItem(), fis, (int) SF.length())) {
                    empty();
                } else {
                    System.out.println("failed");
                }
            } else {
                if (IA.addExpense(tripDrop.getSelectedItem(), typeDrop.getSelectedItem(), currDrop.getSelectedItem(), amountField.getText(), year.getSelectedItem() + "-" + month.getSelectedItem() + "-" + day.getSelectedItem(), null, 0)) {
                    empty();
                }
            }
        } catch (Exception e) {
            System.out.println("error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tripLabe = new javax.swing.JLabel();
        tripDrop = new javax.swing.JComboBox<String>();
        amountLabel = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        typeDrop = new javax.swing.JComboBox<String>();
        currLabel = new javax.swing.JLabel();
        currDrop = new javax.swing.JComboBox<String>();
        subButton = new javax.swing.JButton();
        tripButton = new javax.swing.JButton();
        viewButton = new javax.swing.JButton();
        month = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        day = new javax.swing.JComboBox<String>();
        jLabel5 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        year = new javax.swing.JComboBox();
        selFileButton = new javax.swing.JButton();
        imgLabel = new javax.swing.JLabel();

        tripLabe.setText("Trip");

        tripDrop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        amountLabel.setText("Amount");

        amountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Type");

        typeDrop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        currLabel.setText("Currency");

        currDrop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        subButton.setText("Submit");
        subButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subButtonActionPerformed(evt);
            }
        });

        tripButton.setText("Add Trip");
        tripButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tripButtonActionPerformed(evt);
            }
        });

        viewButton.setText("View Expenses");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("-");

        day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("-");

        dateLabel.setText("Date (MM-DD-YYYY)");

        year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        selFileButton.setText("Select File");
        selFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selFileButtonActionPerformed(evt);
            }
        });

        imgLabel.setText("Receipt Image");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tripLabe)
                    .addComponent(tripDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currLabel)
                    .addComponent(currDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amountLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tripButton)
                                    .addComponent(viewButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(dateLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imgLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(selFileButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(subButton)))))))
                .addGap(67, 154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tripLabe)
                    .addComponent(jLabel1)
                    .addComponent(currLabel)
                    .addComponent(amountLabel)
                    .addComponent(dateLabel)
                    .addComponent(imgLabel))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tripDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(subButton)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selFileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(tripButton)
                .addGap(18, 18, 18)
                .addComponent(viewButton)
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void subButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subButtonActionPerformed
        expense();
    }//GEN-LAST:event_subButtonActionPerformed

    private void tripButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tripButtonActionPerformed
        IA.base.showPanel(4);
    }//GEN-LAST:event_tripButtonActionPerformed

    private void amountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFieldActionPerformed
        expense();
    }//GEN-LAST:event_amountFieldActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        IA.base.showPanel(5);
    }//GEN-LAST:event_viewButtonActionPerformed

    private void selFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selFileButtonActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int returnValue = jfc.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            SF = jfc.getSelectedFile();
            selFileButton.setText(SF.getName());
            System.out.println(SF.getAbsolutePath());
        }
    }//GEN-LAST:event_selFileButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JComboBox<String> currDrop;
    private javax.swing.JLabel currLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JButton selFileButton;
    private javax.swing.JButton subButton;
    private javax.swing.JButton tripButton;
    private javax.swing.JComboBox<String> tripDrop;
    private javax.swing.JLabel tripLabe;
    private javax.swing.JComboBox<String> typeDrop;
    private javax.swing.JButton viewButton;
    private javax.swing.JComboBox year;
    // End of variables declaration//GEN-END:variables
}
