/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ia;

import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.ResultSet;
import javax.imageio.ImageIO;

/**
 *
 * @author Varun Jasti
 */
public class ViewTripExpenses extends javax.swing.JPanel {

    private static String user;
    private static String name;
    private static String trip;
    private static String type;

    /**
     * Creates new form ViewTripExpenses
     */
    public ViewTripExpenses() {
        initComponents();
        expTable.getColumnModel().getColumn(1).setPreferredWidth(15);
        expTable.getColumnModel().getColumn(3).setPreferredWidth(15);
    }

    public void setUser(String user) {
        this.user = user;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setTrip(String trip) {
        this.trip = trip;
    }

    public void setType(String type) {
        this.type = type;
    }

    public void setLabel() {
        label.setText(name + "'s " + trip + " " + type + " Expenses");
    }

    public void setTable() {
        for (int i = 0; i < expTable.getRowCount(); i++) {
            for (int j = 0; j < expTable.getColumnCount(); j++) {
                expTable.setValueAt("", i, j);
            }
        }
        ResultSet rs = IA.adminExps(user, trip, type);
        try {
            for (int i = 0; i < expTable.getRowCount(); i++) {
                rs.next();
                expTable.setValueAt(rs.getString("trip"), i, 0);
                expTable.setValueAt(rs.getString("amount"), i, 1);
                expTable.setValueAt(rs.getString("expenseType"), i, 2);
                expTable.setValueAt(rs.getString("currency"), i, 3);
                expTable.setValueAt(rs.getString("dates"), i, 4);
            }
        } catch (Exception e) {
            System.out.println("error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        expTable = new javax.swing.JTable();
        summaryButton = new javax.swing.JButton();
        viewImgButton = new javax.swing.JButton();

        label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label.setText("jLabel1");

        expTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Trip", "Amount", "Type", "Currency", "Date"
            }
        ));
        jScrollPane1.setViewportView(expTable);

        summaryButton.setText("Summary");
        summaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryButtonActionPerformed(evt);
            }
        });

        viewImgButton.setText("View Image");
        viewImgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewImgButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label)
                        .addContainerGap(714, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewImgButton)
                            .addComponent(summaryButton))
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(summaryButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewImgButton)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void summaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryButtonActionPerformed
        IA.base.showPanel(9);
    }//GEN-LAST:event_summaryButtonActionPerformed

    private void viewImgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewImgButtonActionPerformed
        int r = expTable.getSelectedRow();
        ResultSet rs = IA.viewImg(trip, expTable.getValueAt(r, 1), type, expTable.getValueAt(r, 3), expTable.getValueAt(r, 4), user);
        try {
            rs.next();
            if (rs.getString("images") == null) {
                ViewImg frame = new ViewImg();
                frame.setVisible(true);
            } else {
                Blob blob = rs.getBlob("images");
                InputStream in = blob.getBinaryStream();
                BufferedImage img = ImageIO.read(rs.getBinaryStream("images"));
                ViewImg frame = new ViewImg(img);
                frame.setVisible(true);
            }
        } catch (Exception e) {
            System.out.println("error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_viewImgButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable expTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JButton summaryButton;
    private javax.swing.JButton viewImgButton;
    // End of variables declaration//GEN-END:variables
}
