package ia;

import java.sql.*;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * @author jastvar21
 */
public class ViewExpenses extends javax.swing.JPanel implements TableModelListener {

    /**
     * Creates new form ViewExpenses
     */
    public ViewExpenses() {
        initComponents();
        expensesTable.getModel().addTableModelListener(this);
    }
    
    @Override
    public void tableChanged(TableModelEvent e){
        int r = e.getFirstRow();
        int c = e.getColumn();
        IA.updateExps(expensesTable.getValueAt(r, 0), expensesTable.getValueAt(r, 1), expensesTable.getValueAt(r, 2), expensesTable.getValueAt(r, 3), expensesTable.getValueAt(r, 4), c);
        System.out.println(r + " " + c);
    }

    public void updateTable() {
        expensesTable.getModel().removeTableModelListener(this);
        ResultSet rs = IA.getExps(IA.base.getUser());
        try {
            for (int i = 0; i < expensesTable.getRowCount(); i++) {
                rs.next();
                expensesTable.setValueAt(rs.getString("trip"), i, 0);
                expensesTable.setValueAt(rs.getString("amount"), i, 1);
                expensesTable.setValueAt(rs.getString("expenseType"), i, 2);
                expensesTable.setValueAt(rs.getString("currency"), i, 3);
                expensesTable.setValueAt(rs.getString("dates"), i, 4);
            }
        } catch (Exception e) {
            System.out.println("error");
        }
        expensesTable.getModel().addTableModelListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        expensesTable = new javax.swing.JTable();
        expensesLabel = new javax.swing.JLabel();
        addExpButton = new javax.swing.JButton();
        delExpButton = new javax.swing.JButton();

        expensesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, "", null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Trip", "Amount", "Type", "Currency", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(expensesTable);
        if (expensesTable.getColumnModel().getColumnCount() > 0) {
            expensesTable.getColumnModel().getColumn(0).setResizable(false);
            expensesTable.getColumnModel().getColumn(1).setResizable(false);
            expensesTable.getColumnModel().getColumn(2).setResizable(false);
            expensesTable.getColumnModel().getColumn(3).setResizable(false);
            expensesTable.getColumnModel().getColumn(4).setResizable(false);
        }

        expensesLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        expensesLabel.setText("Expenses");

        addExpButton.setText("Add Expenses");
        addExpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExpButtonActionPerformed(evt);
            }
        });

        delExpButton.setText("Delete Selected Row(s)");
        delExpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delExpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(556, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addExpButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(expensesLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delExpButton)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(expensesLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(addExpButton))
                    .addComponent(delExpButton))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addExpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExpButtonActionPerformed
        IA.base.showPanel(3);
    }//GEN-LAST:event_addExpButtonActionPerformed

    private void delExpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delExpButtonActionPerformed
        expensesTable.getModel().removeTableModelListener(this);
        int[] rows = expensesTable.getSelectedRows();
        for (int i = 0; i < rows.length; i++) {
            IA.deleteExp(expensesTable.getValueAt(rows[i], 0), expensesTable.getValueAt(rows[i], 1), expensesTable.getValueAt(rows[i], 2), expensesTable.getValueAt(rows[i], 3), expensesTable.getValueAt(rows[i], 4));
        }
        updateTable();
        expensesTable.getModel().addTableModelListener(this);
    }//GEN-LAST:event_delExpButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExpButton;
    private javax.swing.JButton delExpButton;
    private javax.swing.JLabel expensesLabel;
    private javax.swing.JTable expensesTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
